sample_id:
  HG00096: "test"
  HG00259: "test"
  HG00262: "test"
  HG00268: "test"
  HG00419: "test"
  HG00641: "test"
  HG00731: "test"
  HG00732: "test"
  HG00734: "test"
  HG00737: "test"
  HG01048: "test"
  HG01049: "test"
  HG01051: "test"
  HG01054: "test"
  HG01055: "test"
  HG01066: "test"
  HG01094: "test"
  HG01110: "test"
  HG01111: "test"
  HG01112: "test"
  HG01168: "test"
  HG01756: "test"
  HG01757: "test"
  HG01872: "test"
  HG01873: "test"
  HG01886: "test"
  HG01953: "test"
  HG01968: "test"
  HG02014: "test"
  HG02057: "test"
  NA06986: "test"
  NA11918: "test"
  NA12275: "test"
  NA18522: "test"
  NA18853: "test"
  NA18870: "test"
  NA18912: "test"
  NA19102: "test"
  NA19130: "test"
  NA19172: "test"
  NA19238: "test"
  NA19334: "test"
  NA19346: "test"
  NA19347: "test"
  NA19471: "test"
  NA19474: "test"
  NA19625: "test"
  NA19648: "test"
  NA20313: "test"
  NA20502: "test"
read_length:
  "20" : "test"
  "25" : "test"
  "30": "test"
  "35": "test"
  "45": "test"
  "55": "test"
  "65": "test"
subsample:
  "1": "test"
  "2": "test"
  "5": "test"
  "10": "test"
  "20": "test"
  "50": "test"
